// JsFromRoutes CacheKey a873b0f89cbed40711ce3fab747cb2dd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as apiV1Appointments } from './Api/V1/AppointmentsApi'
export { default as apiV1Clients } from './Api/V1/ClientsApi'
export { default as apiV1Movements } from './Api/V1/MovementsApi'
export { default as apiV1Sessions } from './Api/V1/SessionsApi'
