// JsFromRoutes CacheKey 3393ba96f10a90e75f14cbdfa837acd7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/appointments'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/appointments'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/appointments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/appointments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/appointments/:id'),
}
