// JsFromRoutes CacheKey a48f48feda796b93248ecb4493c9a459
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/clients'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/clients'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/clients/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/clients/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/clients/:id'),
}
