// JsFromRoutes CacheKey 7e8fec069d51d60781a3abc4705537fa
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/movements'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/movements'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/movements/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/movements/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/movements/:id'),
}
