// JsFromRoutes CacheKey 29a2fce10940c0841a9a09d5c9048421
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/sessions'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/sessions'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/sessions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/sessions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/sessions/:id'),
}
